Repository Cloudible/GCP, pull requests merged in 2025-08, with the labels that each got.

#8 [feat] 구글 OAuth 로그인으로 GCP API 사용
  src/main/java/com/gcp/domain/discord/entity/DiscordUser.java
  src/main/java/com/gcp/domain/discord/repository/DiscordUserRepository.java
  src/main/java/com/gcp/domain/gcp/service/GcpService.java
  src/main/java/com/gcp/domain/gcp/util/GcpAuthUtil.java
  src/main/java/com/gcp/domain/oauth2/controller/OAuthController.java
  src/main/java/com/gcp/domain/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/gcp/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/gcp/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/gcp/domain/oauth2/util/CookieUtils.java
  src/main/java/com/gcp/domain/oauth2/util/TokenEncryptConverter.java
  src/main/java/com/gcp/global/config/SecurityConfig.java
  src/main/java/com/gcp/global/properties/CryptoProperties.java
  src/main/resources/application.yml
Labels: in: auth, in: api, status: needs feedback, priority: medium, type: feature

#14 [feat] GCP 방화벽 조회 및 생성, 삭제
  src/main/java/com/gcp/domain/discord/service/GcpBotService.java
  src/main/java/com/gcp/domain/gcp/service/GcpService.java
  src/main/java/com/gcp/global/config/DiscordBotConfig.java
Labels: in: api, status: done, priority: medium, type: feature

#17 [fix] 예외 처리 개선
  .github/workflows/deploy.yml
  src/main/java/com/gcp/domain/discord/service/GcpBotService.java
  src/main/java/com/gcp/domain/gcp/service/GcpService.java
Labels: in: api, status: needs feedback, priority: medium, type: bug

#18 [feat] VM 생성 시 Debian/Ubuntu OS 버전 추가
  src/main/java/com/gcp/domain/discord/service/GcpBotService.java
  src/main/java/com/gcp/domain/gcp/service/GcpService.java
  src/main/java/com/gcp/domain/gcp/util/GcpImageUtil.java
  src/main/java/com/gcp/global/config/DiscordBotConfig.java
Labels: in: api, status: done, priority: medium, type: feature

#23 [feat] 액세스 토큰 재발급 로직 AOP로 일괄 적용
  src/main/java/com/gcp/domain/gcp/aop/RequiredValidToken.java
  src/main/java/com/gcp/domain/gcp/aop/TokenAspect.java
  src/main/java/com/gcp/domain/gcp/service/GcpService.java
Labels: in: auth, in: api, status: needs feedback, priority: medium, type: feature

#25 [feat] 프로젝트 ID, 인스턴스 Zone 하드 코딩 제거
  src/main/java/com/gcp/domain/discord/service/DiscordUserService.java
  src/main/java/com/gcp/domain/discord/service/GcpBotService.java
  src/main/java/com/gcp/domain/gcp/service/GcpProjectCommandServiceImpl.java
  src/main/java/com/gcp/domain/gcp/service/GcpService.java
  src/main/java/com/gcp/domain/gcp/util/GcpZones.java
  src/main/java/com/gcp/global/config/DiscordBotConfig.java
Labels: in: api, status: in progress, priority: high, type: feature
